#!/bin/bash
puppet apply --codedir /data/puppetarium/ --modulepath /data/puppetarium/modules --fileserverconfig=/data/puppetarium/fileserver.conf /data/puppetarium/environments/production/manifests/site/
